openapi: 3.0.1

info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1

servers:
  - url: /

paths:
  /messages/key:
    post:
      tags:
        - message-controller
      summary: 'Update the master-key fragment for the Session-Key [Authorization:
        Role: technical]'
      operationId: updateKey
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/MasterKeyDTO'
        required: true
      responses:
        202:
          description: ACCEPTED - key was successfully inserted
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        409:
          description: CONFLICT - there was a key in the service
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []
      x-codegen-request-body-name: key

  /messages/new:
    post:
      tags:
        - message-controller
      summary: 'Add new Rocket.Chat message [Authorization: Role: user, consultant,
        technical]'
      operationId: createMessage
      parameters:
        - name: RCToken
          in: header
          required: true
          schema:
            type: string
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
        - name: RCGroupId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/MessageDTO'
        required: true
      responses:
        201:
          description: CREATED - message was successfully created
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []
      x-codegen-request-body-name: Message

  /messages/feedback/new:
    post:
      tags:
        - message-controller
      summary: 'Add new Rocket.Chat message to feedback chat [Authorization: authority
        for feedback chat]'
      operationId: createFeedbackMessage
      parameters:
        - name: RCToken
          in: header
          required: true
          schema:
            type: string
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
        - name: RCFeedbackGroupId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/MessageDTO'
        required: true
      responses:
        201:
          description: CREATED - message was successfully created
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []
      x-codegen-request-body-name: Message

  /messages:
    get:
      tags:
        - message-controller
      summary: 'Get Rocket.Chat message stream [Authorization: Role: user, consultant]'
      operationId: getMessageStream
      parameters:
        - name: RCToken
          in: header
          required: true
          schema:
            type: string
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
        - name: rcGroupId
          in: query
          description: Rocket.Chat roomId
          required: true
          schema:
            type: string
        - name: offset
          in: query
          description: Number of items where to start in the query (0 = first item)
          required: true
          schema:
            type: integer
        - name: count
          in: query
          description: Number of item which are being returned (0 = all)
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK - successfull operation
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MessageStreamDTO'
        204:
          description: NO CONTENT - no messages available
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []

  /messages/forward:
    post:
      tags:
        - message-controller
      summary: 'Forward a Rocket.Chat message to another group [Authorization: Role:
        u25-consultant]'
      operationId: forwardMessage
      parameters:
        - name: RCToken
          in: header
          required: true
          schema:
            type: string
        - name: RCUserId
          in: header
          required: true
          schema:
            type: string
        - name: RCGroupId
          in: header
          required: true
          schema:
            type: string
      requestBody:
        description: Body description
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/ForwardMessageDTO'
        required: true
      responses:
        201:
          description: CREATED - message was successfully created
        400:
          description: BAD REQUEST - invalid/incomplete request or body object
        401:
          description: UNAUTHORIZED - no/invalid Keycloak token
        403:
          description: FORBIDDEN - no/invalid role/authorization
        500:
          description: INTERNAL SERVER ERROR - server encountered unexpected condition
      security:
        - Bearer: []
      x-codegen-request-body-name: Message

components:
  schemas:
    MessageDTO:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: "Lorem ipsum dolor sit amet, consetetur..."
        sendNotification:
          type: boolean
          example: "true"

    MessageStreamDTO:
      type: object
      required:
        - messages
        - count
        - offset
        - total
        - success
        - cleaned
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/MessagesDTO'
        count:
          type: string
          example: "2"
        offset:
          type: string
          example: "0"
        total:
          type: string
          example: "2"
        success:
          type: string
          example: "true"
        cleaned:
          type: string
          example: "true"

    MessagesDTO:
      type: object
      required:
        - _id
        - rid
        - msg
        - ts
        - u
        - unread
        - mentions
        - channels
        - _updatedAt
      properties:
        _id:
          type: string
          example: "M73fE4WhYF4peYB3s"
        alias:
          $ref: '#/components/schemas/ForwardMessageDTO'
        rid:
          type: string
          example: "fR2Rz7dmWmHdXE8uz"
        msg:
          type: string
          example: "Lorem ipsum dolor sit amet, consetetur..."
        ts:
          type: string
          description: "Full qualified timestamp"
          example: "2018-11-15T09:33:00.057Z"
        u:
          $ref: '#/components/schemas/UserDTO'
        unread:
          type: boolean
        mentions:
          type: array
          items:
            type: string
        channels:
          type: array
          items:
            type: string
        _updatedAt:
          type: string
          description: "Full qualified timestamp"
          example: "2018-11-15T09:33:00.057Z"
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/AttachmentDTO'
        file:
          $ref: '#/components/schemas/FileDTO'

    ForwardMessageDTO:
      type: object
      required:
        - message
        - timestamp
        - username
        - rcUserId
      properties:
        message:
          type: string
          example: "Lorem ipsum dolor sit amet, consetetur..."
        timestamp:
          type: string
          description: "Full qualified timestamp"
          example: "2018-11-15T09:33:00.057Z"
        username:
          type: string
          example: "asker23"
        rcUserId:
          type: string
          example: "ag89h3tjkerg94t"

    UserDTO:
      type: object
      required:
        - _id
        - username
        - name
      properties:
        _id:
          type: string
          example: "vppRFqjrzTsTZ6iEn"
        username:
          type: string
          example: "test"
        name:
          type: string
          example: "Mustermax"

    AttachmentDTO:
      type: object
      required:
        - title
        - type
        - description
        - title_link
        - title_link_download
        - image_url
        - image_type
        - image_size
        - image_preview
      properties:
        title:
          type: string
          example: "filename.png"
        type:
          type: string
          example: "file"
        description:
          type: string
          example: "Description"
        title_link:
          type: string
          example: "/file-upload/ijxact7nd5SMpSwiS/file.png"
        title_link_download:
          type: boolean
          example: "true"
        image_url:
          type: string
          example: "/file-upload/ijxact7nd5SMpSwiS/file.png"
        image_type:
          type: string
          example: "image/png"
        image_size:
          type: integer
          example: "36461"
        image-preview:
          type: string
          example: "/9j/2wBDAAYEBQYFBAYGBQY"

    FileDTO:
      type: object
      required:
        - _id
        - name
        - type
      properties:
        _id:
          type: string
          example: "M73fE4WhYF4peYB3s"
        name:
          type: string
          example: "filename.jpg"
        type:
          type: string
          example: "image/jepg"

    MasterKeyDTO:
      type: object
      required:
        - masterKey
      properties:
        masterKey:
          type: string
          example: "sdj8wnFNASj324!ksldf9"

  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
